### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by evhend** [UBC-MDS/DSCI_522_group-307#37]
good concise results in the form of tables 
 - if someone understand something about data science, can glean useful information  
 
Improvement:
- not a clear conclusion 
- provide use cases on how to use the results  
- questions for use cases

Code:
- docstrings
- tests
- conciseness/readability  
- functions need to be more modularized

**Comment by reikookamoto** [comment]
Issues we addressed: 
- Added docstrings
- Added tests
- Increased readability by using dynamic variables to report
