### ISSUE TITLE
Team contract draft

### ISSUE THREAD

**Issue by reikookamoto** [UBC-MDS/DSCI_522_group-307#4]
Hey guys, here is a draft of the team contract based on what we've discussed today. Please comment below if you think something should be added or changed. 

How will work be distributed among team members?
- Check in at the beginning of each week (preferably Monday) either in person or via Slack
- Clarify the deliverables of the week's milestone
- Delegate tasks - respecting personal preferences whenever possible
- Create a to-do list in the form of a GitHub issue that summarizes what each group member will do that week 
- Stick to an internal deadline of Friday evening - allow group members to focus on other assignments during the weekend

Group meetings:
- Twice a week: Monday (preferably) and Thursday (during lab)
- Write meeting minutes in the form of a GitHub issue
- During Thursday meetings, if possible, forecast what's expected in the following week's milestone

Other notes on communication:
- When issues arise, communicate with each other (via Slack, GitHub issues) promptly - important to have as much time as possible to help one another and work out the kinks
- If anyone feels that s/he has been assigned an unfair amount of work (in terms of workload or complexity), make others aware so that the work can be redistributed
- If anyone is unable to physically attend meetings or labs, s/he is encouraged to be active on Slack so s/he can participate in the decision-making process actively

**Comment by evhend** [comment]
Looks good Reiko. I would add:
- meeting minutes (Thursday labs) to be added as bullet points as a github issue
- we should try to forecast the following week's work on Thursdays (although I realize that the milestones will not be available)
- if anyone feels that they have a disproportional amount of work, make the other team members aware so that we can redistribute the work

**Comment by saurav193** [comment]
This looks fine. I would like to add : 

1. If any task implementation problem occurs(like R project in Dash last block) for any member and meeting deadline is difficult, he/she should let others know beforehand and redistribute the extra work.

**Comment by reikookamoto** [comment]
Contract has been updated accordingly. Ready to be copy and pasted into an .md file and submitted as part of this week's milestone via github.ubc.ca
