### ISSUE TITLE
Visualizations Feedback!

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_group-307#58]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- Figure 1:
	- - [x] Interesting idea to split by income levels! 
	- - [x] This arrangement looks good !
- Tables:
	- - [x] Very nice table headers!
	- - [x] kudos for rounding your values to 3 digits - most people don't do this but doing it really improves readability. If it was me, I'd go to 2 sig figs but it's up to you
	- - [x] I like that you ranked the tables by weight/importance!
- - [x] This is not something standard, but I personally would have created a dictionary with the column names as keys and a more human readable name as a value. This is just something to keep in mind in the future. The feature names aren't super intuitive so you have to hunt around in the text for their interpretation. Another way is to add a table in the appendix with the column name and its corresponding human readable interpretation 
- - [x] I think your figure and tables are very clear and appropriate for your project and research question. Nice work!

**Comment by reikookamoto** [comment]
Thanks for the feedback! Increasing the legibility of feature names is something we'll keep in mind for future projects!
